"""create threat indicators table

Revision ID: b1a02ee65491
Revises: 146ae28ec93c
Create Date: 2026-08-27 23:46:39.720996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a02ee65491'
down_revision: Union[str, Sequence[str], None] = '146ae28ec93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('indicator_value', sa.String(length=500), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_indicators_indicator_type'), 'threat_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_indicators_indicator_value'), 'threat_indicators', ['indicator_value'], unique=True)
    op.create_index(op.f('ix_threat_indicators_is_active'), 'threat_indicators', ['is_active'], unique=False)
    op.create_index(op.f('ix_threat_indicators_last_seen_at'), 'threat_indicators', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_threat_indicators_severity'), 'threat_indicators', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_indicators_threat_type'), 'threat_indicators', ['threat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_indicators_threat_type'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_severity'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_last_seen_at'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_is_active'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_value'), table_name='threat_indicators')
    op.drop_index(op.f('ix_threat_indicators_indicator_type'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    # ### end Alembic commands ###
