import {
  Activity,
  AlertTriangle,
  BrainCircuit,
  FileChartColumn,
  RefreshCw,
  ShieldAlert,
} from 'lucide-react'
import { Button } from '../../components/ui/Button'
import { getApiErrorMessage } from '../../lib/api-error'
import { DashboardCard } from '../dashboard/components/DashboardCard'
import { DashboardSkeleton } from '../dashboard/components/DashboardSkeleton'
import { RankedMetricList } from '../dashboard/components/RankedMetricList'
import { RiskDistributionChart } from '../dashboard/components/RiskDistributionChart'
import { StatCard } from '../dashboard/components/StatCard'
import { VerdictDonutChart } from '../dashboard/components/VerdictDonutChart'
import { toMetricData } from '../dashboard/dashboard-utils'
import { formatOperationTimestamp } from '../operations/operation-utils'
import { useSecurityReport } from './useSecurityReport'

export function ReportsPage() {
  const query = useSecurityReport()

  if (query.isLoading)
    return (
      <div aria-label="Loading security report">
        <DashboardSkeleton />
      </div>
    )
  if (query.error || !query.data)
    return (
      <main className="grid min-h-[calc(100vh-4rem)] place-items-center p-6 text-center">
        <div className="max-w-md">
          <AlertTriangle className="mx-auto size-10 text-rose-400" />
          <p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-rose-300">
            Security report unavailable
          </p>
          <h1 className="mt-3 text-2xl font-semibold text-white">
            The current security summary could not be generated
          </h1>
          <p className="mt-3 text-sm leading-6 text-slate-500">
            {getApiErrorMessage(query.error)}
          </p>
          <Button
            className="mt-6"
            onClick={() => void query.refetch()}
            disabled={query.isFetching}
          >
            <RefreshCw
              className={`size-4 ${query.isFetching ? 'animate-spin' : ''}`}
            />
            {query.isFetching ? 'Retrying' : 'Try again'}
          </Button>
        </div>
      </main>
    )

  const report = query.data.report
  const data = report.dashboard
  return (
    <main className="p-5 md:p-7 xl:p-8">
      <div className="mx-auto max-w-[1500px]">
        <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
          <div>
            <p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-cyan-400">
              <FileChartColumn className="size-3.5" /> Security reporting
            </p>
            <h1 className="mt-2 text-2xl font-semibold tracking-[-0.025em] text-white md:text-3xl">
              {report.report_title}
            </h1>
            <p className="mt-2 text-sm text-slate-500">
              Current persisted security analytics snapshot.
            </p>
          </div>
          <Button
            variant="secondary"
            onClick={() => void query.refetch()}
            disabled={query.isFetching}
          >
            <RefreshCw
              className={`size-4 ${query.isFetching ? 'animate-spin' : ''}`}
            />
            Generate current report
          </Button>
        </div>

        <section
          className="surface-card mt-5 grid gap-4 px-5 py-4 text-xs sm:grid-cols-3"
          aria-label="Report metadata"
        >
          <div>
            <p className="font-bold uppercase tracking-[0.12em] text-slate-600">
              Generated
            </p>
            <p className="mt-1.5 text-slate-300">
              {formatOperationTimestamp(report.generated_at)}
            </p>
          </div>
          <div>
            <p className="font-bold uppercase tracking-[0.12em] text-slate-600">
              Generated by
            </p>
            <p className="mt-1.5 text-slate-300">
              {report.generated_by_username}
            </p>
          </div>
          <div>
            <p className="font-bold uppercase tracking-[0.12em] text-slate-600">
              User ID
            </p>
            <p className="mt-1.5 font-mono text-slate-300">
              {report.generated_by_user_id}
            </p>
          </div>
        </section>

        <section
          className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"
          aria-label="Report summary metrics"
        >
          <StatCard
            label="Total events"
            value={data.total_events}
            detail="Persisted events included in this snapshot"
            icon={Activity}
            tone="cyan"
          />
          <StatCard
            label="Critical risk"
            value={data.risk_levels.critical}
            detail="Critical rule-analysis classifications"
            icon={ShieldAlert}
            tone="rose"
          />
          <StatCard
            label="Suspicious verdicts"
            value={data.verdicts.suspicious}
            detail="Suspicious AI classifications"
            icon={BrainCircuit}
            tone="orange"
          />
          <StatCard
            label="AI anomalies"
            value={data.anomalies}
            detail="Anomalous events identified"
            icon={FileChartColumn}
            tone="violet"
          />
        </section>

        <section className="mt-4 grid gap-4 xl:grid-cols-5">
          <DashboardCard
            title="Risk level distribution"
            description="Rule-analysis classifications in this snapshot"
            className="xl:col-span-3"
          >
            <RiskDistributionChart riskLevels={data.risk_levels} />
          </DashboardCard>
          <DashboardCard
            title="AI verdict distribution"
            description="Benign and suspicious AI classifications"
            className="xl:col-span-2"
          >
            <VerdictDonutChart verdicts={data.verdicts} />
          </DashboardCard>
        </section>

        <section className="mt-4 grid gap-4 lg:grid-cols-3">
          <DashboardCard
            title="Event categories"
            description="Observed event-type totals"
          >
            <RankedMetricList
              data={toMetricData(data.event_types)}
              emptyLabel="No event category data in this report"
            />
          </DashboardCard>
          <DashboardCard
            title="Attack categories"
            description="AI-classified attack activity"
          >
            <RankedMetricList
              data={toMetricData(data.attack_categories)}
              emptyLabel="No attack category data in this report"
            />
          </DashboardCard>
          <DashboardCard
            title="MITRE ATT&CK activity"
            description="Techniques mapped during event analysis"
          >
            <RankedMetricList
              data={toMetricData(data.mitre_techniques)}
              emptyLabel="No MITRE technique data in this report"
              preserveLabels
            />
          </DashboardCard>
        </section>
      </div>
    </main>
  )
}
